### ISSUE TITLE
Adding new organisations to registry

### ISSUE THREAD

**Issue by indigotrust** [ThreeSixtyGiving/data.threesixtygiving.org#14]
Having added one new organisation (Gatsby) via the http://data.threesixtygiving.org/node/add/group link, I am now getting an access denied message when trying to access the same link and no apparent way of registering any more organisations.

**Comment by practicalparticipation** [comment]
Hello Matt

We have a limit on number of organisations a standard user can create, to try and avoid people getting confused with the system - but I'd tried to create an over-ride for you.

I've just updated this now: can you try again? Otherwise I'll remove the node limit for now - and we can look at whether we need to re-implement it later.

**Comment by indigotrust** [comment]
Thanks, Tim. Just tried reloading and logging in/out, but still getting access denied. I'm assuming responsibility for adding all publishing SFCTs at the moment, but that may change if others in the office want to take on that responsibility. I may also need to invite Dave Martindale to those orgs at a later date, but for now want to get the basic profiles set up before bothering anybody else here.

**Comment by practicalparticipation** [comment]
Ok. I've removed the limit entirely to see if that helps.

If its still not working then I'll dive into the logs more to see what
might be going on here.


On Fri, Mar 13, 2015 at 12:27 PM, indigotrust <notifications@github.com>
wrote:

> Thanks, Tim. Just tried reloading and logging in/out, but still getting
> access denied. I'm assuming responsibility for adding all publishing SFCTs
> at the moment, but that may change if others in the office want to take on
> that responsibility. I may also need to invite Dave Martindale to those
> orgs at a later date, but for now want to get the basic profiles set up
> before bothering anybody else here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/data.threesixtygiving.org/issues/14#issuecomment-78949467>
> .
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by indigotrust** [comment]
Yep, seems to let me add new orgs now. Thanks
