### ISSUE TITLE
Edit logos on homepage

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/data.threesixtygiving.org#16]
Rather than draw from DKAN, the logos for "supporters" should be from a static list

**Comment by caprenter** [comment]
Although, DKAN is currently the single source of truth for the logo's and associated data (e.g. name of organisation associated with the logo, datasets etc)

A static list is one option.

Other options could be to show a defined number, but rotate them for example.

Might be worth trying to define what the purpose of this section is.

**Comment by stevieflow** [comment]
I think we close this specific issue, as our plan is to draw supporter logos via the ticket in https://github.com/ThreeSixtyGiving/website/issues/65

Reopen if otherwise
