### ISSUE TITLE
Notify support when new group is created

### ISSUE THREAD

**Issue by practicalparticipation** [ThreeSixtyGiving/data.threesixtygiving.org#4]
An e-mail alert should be sent to support@threesixtygiving.org when a new group is created. 

If possible, this would be sent with the 'from' e-mail address of the user creating the group, as this would allow us to match it to / create a support record in the CRM for that user.

**Comment by pmackay** [comment]
Should be enabled on live, but not sure how to test if emails are coming into tracker.

**Comment by practicalparticipation** [comment]
I've just created a new group - and watching at https://standardsupport.plan.io/projects/three-sixty-giving/issues to see if an issue gets created from the incoming mail...

**Comment by practicalparticipation** [comment]
Tested and working.
