### ISSUE TITLE
On completing registration, user should be redirected to homepage

### ISSUE THREAD

**Issue by practicalparticipation** [ThreeSixtyGiving/data.threesixtygiving.org#5]
At the moment, following on from clicking the link to confirm a user account, and updating password, the user simply stays on the edit user page. 

This is themed like an admin page, rather than in the general design - and so doesn't lead the user into where they can add their organisation and datasets.

**Comment by pmackay** [comment]
I can get the user edit page to look like the site theme rather than admin. But I've tried a number of experiments to redirect users after saving their password using Rules and other settings but not resolved it so far. Would it be sufficient if it had the site theme for now?

**Comment by practicalparticipation** [comment]
I think that would work for now - yes.

**Comment by pmackay** [comment]
User edit page now shown in site theme.

**Comment by practicalparticipation** [comment]
Tested and working.
