### ISSUE TITLE
Create view(s) to step user through organisation and dataset addition

### ISSUE THREAD

**Issue by practicalparticipation** [ThreeSixtyGiving/data.threesixtygiving.org#7]
To help users create their datasets, I suggest that we create a set of views / blocks that work roughly as follows (open to discussion: this just as an initial sketch):

When the user first logs in, and has no groups associated with their account:

![image](https://cloud.githubusercontent.com/assets/477172/6025523/ff9f185a-abca-11e4-94b6-391e22988b68.png)

When the user is associated with a group, but has no listed datasets:

![image](https://cloud.githubusercontent.com/assets/477172/6025529/1274e90a-abcb-11e4-86e3-673cb3b769f4.png)

When the user is a member of a group with associated datasets:

![image](https://cloud.githubusercontent.com/assets/477172/6025534/21fe84e4-abcb-11e4-92b5-f542c3b64d23.png)

**Comment by pmackay** [comment]
@practicalparticipation do you see this as a tab on the user's profile? Or somewhere else in menu structure?

**Comment by practicalparticipation** [comment]
I was thinking it could even be a block shown at the top of all pages for a logged in, non-admin user. 

The main reasons someone would be logged in would be to update their data - so presenting this to them front-and-center makes reasonable sense...

**Comment by pmackay** [comment]
Updated dev with a first stab at this http://dev-360giving.pantheon.io/dashboard. Currently it is still a separate page, but could turn into a block on all pages if you feel that's best?

**Comment by practicalparticipation** [comment]
Great. 

I've had a very quick test - I think fine to leave on it's own page for now, and we can do some user testing to see how well people find that. 

From quick test:

* If I'm a group member, but not owner, I can't edit the group (this is probably a more general permissions issue we should fix. We should set it so that any group members can edit and update the group they are part of).
* If I had no associated datasets it wasn't offering me a link to create them;

I didn't test with a new user- but have just registered one, pending approval.

**Comment by practicalparticipation** [comment]
View for the user without a group looks good :)

**Comment by pmackay** [comment]
Pushed changes to live. Added link if to create if no datasets.

Group member should be able to edit group on live, but need to test.

**Comment by practicalparticipation** [comment]
Just tested.

Most is working, apart from the user should not be shown the 'Add Dataset'
link unless they are part of a group.

Hope this is possible to implement with views logic.

On Fri, Feb 13, 2015 at 8:32 PM, Paul Mackay <notifications@github.com>
wrote:

> Pushed changes to live. Added link if to create if no datasets.
>
> Group member should be able to edit group on live, but need to test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/data.threesixtygiving.org/issues/7#issuecomment-74322017>
> .
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by pmackay** [comment]
I tested some other ways to hide the Add dataset link, but style hacks cant work via Views as they are stripped out. For now I've added an extra line to document the point http://test-360giving.pantheon.io/dashboard.

![screen shot 2015-03-02 at 15 24 51](https://cloud.githubusercontent.com/assets/115115/6443703/9457e69a-c0f0-11e4-85ba-89d30914998e.png)
